### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by PMDHA** [smeyn/ZeverSolar#7]
Hi, can somebody help me install this?

**Comment by smeyn** [comment]
other than doing what is in the readme, what help do you need?

**Comment by PMDHA** [comment]
Well I don't understand readme...

F.e. the line: pip install -r requirements.txt does not work. It gives: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by PMDHA** [comment]
Could you perhaps give me a hand...

**Comment by PMDHA** [comment]
Ok, I got a step further, after the command "Run the data collector" I get:

Traceback (most recent call last):
  File "zever.py", line 205, in <module>
    collectData(arguments, conn, verbose)
  File "zever.py", line 164, in collectData
    result = processZeverResponse(content)
  File "zever.py", line 61, in processZeverResponse
    'Registry Key': parts[3],
IndexError: list index out of range

It did load 3049 records in the SQLdatabase. Any help possible?

**Comment by smeyn** [comment]
so you were loadijg records and at one point the response could not be parsed. I suggest yu add a check after the split and do not process the response.
This could very well be the web server returning an invalid response.
